name: Report a Bug ðŸ›
description: Report an issue with Pictogrammers.com.
labels: Bug
body:
  - type: checkboxes
    attributes:
      label: Before You Begin
      description: Please verify that you've followed these steps
      options:
        - label: I have cleared the cache of my browser.
          required: true
        - label: I have tried a different browser to see if it is related to my browser.
          required: true
  - type: markdown
    attributes:
      value: |
        ## The problem
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the issue you are experiencing
      description: Provide a clear and concise description of what the bug is.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the behavior you expected
      description: Describe what you expected to happen or how it should look/behave.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce the issue
      description: |
        Please tell us exactly how to reproduce your issue.
        Provide clear and concise step-by-step instructions.
      value: |
        1.
        2.
        3.
        ...
  - type: input
    attributes:
      label: Which browser are you experiencing the issue?
      placeholder: Google Chrome 88.0.4324.150
      description: Provide the full name and version number.
  - type: input
    attributes:
      label: Which operating system are you using to run this browser?
      placeholder: macOS Ventura 13.1
      description: Provide the OS name and version.
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Note: you can attach screenshots or screen recordings here by
        dragging and dropping files in the field below.